export const countriesList = [
  "Australia",
  "Austria",
  "Azerbaijan",
  "Belgium",
  "Canada",
  "China",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Italy",
  "Japan",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Netherlands",
  "New Zealand",
  "Poland",
  "Portugal",
  "Russia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Turkmenistan",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
];
